### ISSUE TITLE
Is there any update to that? :)

### ISSUE THREAD

**Issue by JulianVolodia** [0x7f454c46/travis-kernel-ci#1]
Hello @0x7f454c46 !

I wonder if there was any updates to Your project. Is it used in-the-wild?

Thanks!

**Comment by 0x7f454c46** [comment]
Nope, I didn't touch it for a while :)

**Comment by JulianVolodia** [comment]
OK, thanks for respond. :) 

As I understand here is helper to prepare some env for testing things on next version of Linux kernel to be released with intensive use of CRIU? I haven't dig into it yet.

What you think about putting efforts to testing some Kernel API using this itself from user-space?

**Comment by 0x7f454c46** [comment]
It was an attempt to separate linux-next testing into a project, originally based on Andrey Vagin's travis-ci hacks.
You can glance at how it used to work [and maybe still works]: https://travis-ci.org/github/avagin/linux

**Comment by JulianVolodia** [comment]
Thank You.
